services:
  admin:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8005:80"
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./admin/.next/static:/usr/share/nginx/html/_next/static:ro
    depends_on:
      - admin
    restart: unless-stopped
