services:
  admin:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - static_assets:/app/.next/static
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_assets:/usr/share/nginx/html/_next/static
    ports:
      - "8006:80"
    depends_on:
      - admin
    restart: unless-stopped

volumes:
  static_assets:
