name: Test and build
on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    name: Node ${{ matrix.node }} sample
    steps:
      # - name: install nvm
      #   run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash

      # - name: source .bashrc
      #   run: source ~/.bashrc

      # - name: check node version
      #   run: nvim install 20

      - name: setup node
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: check node version
        run: node -v

      - name: install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: build app
        run: yarn build

      - name: lint code
        run: npm run lint

      # - name: run tests
      #   run: npm test
