name: Test and build
on:
  push:
    branches: [ main]

jobs:
  build-and-test:
    name: Build and test app
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: setup node
        uses: actions/setup-node@v3

      - name: check node version
        run: node -v

      - name: install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: build app
        run: yarn build

      - name: lint code
        run: npm run lint

      # - name: run tests
      #   run: npm test